apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: argocd
spec:
  project: default
  source:
    chart: odoo
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 21.2.7
    helm:
      releaseName: odoo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
